services:
  core:
    build: ./easm-core
    environment:
      REDIS_URL: redis://redis:6379/0
    ports:
      - "8001:8001"
    depends_on:
      - redis
      - db
    networks: [easm_net]

  worker:
    build: ./easm-core
    command: python -m arq app.tasks.queue.WorkerSettings
    environment:
      REDIS_URL: redis://redis:6379/0
      PYTHONUNBUFFERED: 1
      LOGLEVEL: INFO
    depends_on:
      - core
      - redis
    networks: [easm_net]

  scanner-nmap:
    build: ./scanners/scanner-nmap
    command: python -m arq app.main.WorkerSettings
    environment:
      REDIS_URL: redis://redis:6379/0
      CORE_URL: http://core:8001
      PYTHONUNBUFFERED: 1
      LOGLEVEL: INFO
    depends_on:
      - redis
    networks: [easm_net]

  scanner-masscan:
    build: ./scanners/scanner-masscan
    command: python -m arq app.main.WorkerSettings
    environment:
      REDIS_URL: redis://redis:6379/0
      CORE_URL: http://core:8001
      PYTHONUNBUFFERED: 1
      LOGLEVEL: INFO
    depends_on:
      - redis
    networks: [easm_net]

  scanner-nuclei:
    build: ./scanners/scanner-nuclei
    command: python -m arq app.main.WorkerSettings
    environment:
      REDIS_URL: redis://redis:6379/0
      CORE_URL: http://core:8001
      PYTHONUNBUFFERED: 1
      LOGLEVEL: INFO
    depends_on:
      - redis
    networks: [easm_net]

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    networks: [easm_net]

  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: easm
      POSTGRES_PASSWORD: easm
      POSTGRES_DB: easm
    volumes:
      - db_data:/var/lib/postgresql/data
    networks: [easm_net]

volumes:
  db_data:

networks:
  easm_net:
    driver: bridge