# filepath: /Users/piotrtyrna/Desktop/Reconnity/easm-microservices/easm-core/app/db/migrations/script.py.mako
"""Initial migration

Revision ID: 69fdeff18670
Revises: 
Create Date: 2025-07-02 22:50:09.536891

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '69fdeff18670'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
